blank_issues_enabled: false
contact_links:
  - name: ðŸ“„ General Questions
    url: https://github.com/EnvisionSAI/Envision-Website/discussions
    about: Ask general questions or start discussions here.